### ISSUE TITLE
Show the workflow in an animated gif

### ISSUE THREAD

**Issue by zuphilip** [rmzelle/ref-extractor#11]
I guess that it could help to see the whole workflow with ref-extractor as a small animated gif which can be placed here and on your website. What do you think?

**Comment by rmzelle** [comment]
Uhm, maybe. You suggest covering everything including the import of the CSL JSON into Zotero? Are the current instructions not clear enough? I guess gifs can be explanatory, but they're not very accessible to visually impaired people.

I could also replace the current block of text with a FAQ, which might be easier to navigate. And we could embed https://larsgw.github.io/citation.js/ to support BibTex output, which would make things easier for non-Zotero users.

**Comment by zuphilip** [comment]
The instructions are written clear, but I thought it might be nice to have some visual example. And yes, I guess it makes sense to show the whole workflow also importing into Zotero, because standard user might not know what CSL JSON is. I would see this more like telling a story. You could also use such a GIF for "marketing" use cases like tweeting.

Anyway, I can try to make an example of what I thought about (maybe on the weekend).

**Comment by rmzelle** [comment]
> Anyway, I can try to make an example of what I thought about (maybe on the weekend).

Thanks (I didn't mean to sound overly critical; GIFs can definitely be helpful)! We might also want to see if we can create a GIF for http://editor.citationstyles.org/searchByExample/, since it often confuses users.
