### ISSUE TITLE
Zotero rich text formatting not converted in bibTeX output

### ISSUE THREAD

**Issue by gavinmacaulay** [rmzelle/ref-extractor#25]
If text in a Zotero field uses rich text formatting (as per [this](https://www.zotero.org/support/kb/rich_text_bibliography)), the formatting directives are not translated into TeX/LaTeX appropriate directives. For example, italics in a paper title gives this in the BibTeX output:

`title={{Effect of orientation on broadband acoustic scattering of Antarctic krill {\textless}i{\textgreater}Euphausia superba{\textless}/i{\textgreater}: Implications for inverting zooplankton spectral acoustic signatures for angle of orientation}}`

(the Euphausia superba words should rather be enclosed in `\textit{}`

**Comment by rmzelle** [comment]
@gavinmacaulay, thanks. My tool relies on a third-part software library to generate the BibTeX output, so I reported this upstream: https://github.com/larsgw/citation.js/issues/150. I'll post back here once this is fixed.

**Comment by rmzelle** [comment]
@gavinmacaulay, sorry for the wait, but this should now be fixed (I just updated ref-extractor to use the latest v0.4.0-9 release of citation.js which should include this fix).
