### ISSUE TITLE
Support selection of cited Zotero group library items

### ISSUE THREAD

**Issue by rmzelle** [rmzelle/ref-extractor#29]
Per https://twitter.com/danstillman/status/1141812891542347781, there appears to be a separate syntax for selecting group library items:

`zotero://select/library/items?itemKey=[key1],[key2],[keyn]`
`zotero://select/groups/:groupID/items?itemKey=[key1],[key2],[keyn]`

Within Word .docx documents, the item URIs look like (courtesy to @bwiernik for the group library examples):

`"uris":["http://zotero.org/users/1386342/items/TANS5GUE"]`
`"uris":["http://zotero.org/groups/227594/items/2TK9HDKD"]`
`"uris":["http://zotero.org/groups/2268106/items/A86NXHJE"]`

In view of the selection link syntax, we'll have to provide individual selection links for items cited from a user's personal library, and for items cited from one or more group libraries. Maybe use a button dropdown (https://getbootstrap.com/docs/3.4/components/#btn-dropdowns-single) so the Reference Extractor user can select which library/group to select items for.

**Comment by rmzelle** [comment]
@bwiernik, can you confirm by the way that it's not possible in Zotero to have items from multiple libraries selected at the same time? (if it is possible, we could ask Zotero for a syntax that would allow items to be selected across libraries with a single link, but if it isn't, there is no point)

**Comment by bwiernik** [comment]
Could you make a URI with the syntax that might make it work? There isn’t a way to display multiple libraries in the interface at one time, so it’s not possible to manually select items from multiple libraries.

**Comment by rmzelle** [comment]
> Could you make a URI with the syntax that might make it work?

No, Zotero would likely need to modify its UI code, and would have to adopt a different selection link scheme, e.g. something like `zotero://select/items?itemKey=[key1],[groupID1|key2],[groupID2|key3]`. I'll just look into generating separate selection links for each library for now with the existing syntax, which should work out of the box.

**Comment by rmzelle** [comment]
@bwiernik, let me know how it works for you.
