### ISSUE TITLE
How do you install?

### ISSUE THREAD

**Issue by Tafnab** [rmzelle/ref-extractor#36]
I see the code. I don't see an .xpi file.
I'm assuming it's supposed to be installed as an add-on inside Zotero.
Could you provide installation/build instructions?

**Comment by rmzelle** [comment]
@Tafnab, no, this isn't a plugin for Zotero. You can use Reference Extractor online at https://rintze.zelle.me/ref-extractor/.

**Comment by Tafnab** [comment]
@rmzelle  Sorry about that.
