### ISSUE TITLE
Sync between Zotero and Word document after extraction

### ISSUE THREAD

**Issue by Lycurgue** [rmzelle/ref-extractor#37]
Hi,

Thanks for this tools. Really nice.

I extracted **Zotero** references from a **Word** document in **CSL JSON** format. All went well.
But there is no synchronization between **Zotero** and the document.
When I modify a reference in **Zotero**, the modification does not synchronize in the **Word** document after a refresh.

Is it a normal situation or do I have to do something else?
Do I have to "reactivate" (enter again with _Add/Edit Citation_) in the **Word** document each citation so that **Zotero** will recognize them?

Thanks,

François

**Comment by rmzelle** [comment]
@Lycurgue, there is currently no automated workflow for linking the items extracted with **ref-extractor** with the original items in the extracted Word document. And yes, manually re-inserting the items is the way to go for now.
