### ISSUE TITLE
Select in Zotero is unavaiable

### ISSUE THREAD

**Issue by fschuman** [rmzelle/ref-extractor#41]
Can't click on 'Select in Zotero'. 

MacOs 11.6.8
Zotero 6.0.11 (running and synced)
Browser: Safari, Edge

<img width="641" alt="image" src="https://user-images.githubusercontent.com/11075565/181916602-15befcf8-cb10-4406-b06d-c2ef6901d3c2.png">

**Comment by rmzelle** [comment]
@fschuman, sorry for the late response. One of the explanations for this behavior could be that the Word document in question contained Mendeley citations instead of Zotero citations. Are you certain that this file contained Zotero citations?

**Comment by fschuman** [comment]
The original document I tried should be with Zotero citations, yes, as I don't use Mendeley. 
But now with a test document with 3 Zotero citations only, the extraction works. Also the selection in Zotero.
Perhaps there's another issue with my original document.

**Comment by rmzelle** [comment]
> Perhaps there's another issue with my original document.

There are some troubleshooting steps you could take if you're interested. Retry the original document, copy and paste the contents to a fresh Word document, or save copies of the original document in which you either delete subsets of the in-text citations or add a new citation.

**Comment by fschuman** [comment]
Thanks, I tried those stops, but this particular document seems to have some problem. 
Not worth investigating further however.

**Comment by fschuman** [comment]
I've used it for a couple of other documents, works like a charm. Thanks !
