### ISSUE TITLE
Feature Request: select citations from Mendeley documents in Zotero

### ISSUE THREAD

**Issue by fschuman** [rmzelle/ref-extractor#42]
I've moved from Mendeley to Zotero. It would be super helpful if one could select citations from Mendeley documents in Zotero.

**Comment by rmzelle** [comment]
Hi @fschuman, apologies for the very late reply.

If you only have access to your Mendeley-authored documents, then you could import your extracted references into Zotero, and then manually replace each citation in your document with the matching imported Zotero item. Zotero won't recognize that the newly imported items match the items in your document, and there is not really something about that Reference Extractor can do to change that.
