### ISSUE TITLE
Multiple entires in document

### ISSUE THREAD

**Issue by XZZ154** [rmzelle/ref-extractor#43]
Hi!

I have a highly specific issue. I am working with my thesis which stretched over years. I have written parts 1, 2 and 3 in separate documents and from separate computers. Now I want to assemble the final version. I have copied the content of all three documents to a single documents. The problem is that Zotero does not seem to automatically merge the entries. Most are merged, but some appear twice in the bibiography and is treated separately in my notes. I want to solve the issue without going through one by one all citations. I have found no exact help for my issue on the forums. I have tried to extract the references with this tool from the .docx document, import to my Zotero and then merge all duplicates within my Zotero library, but this seems to have no effect on the document.

Looking forward to your help.

**Comment by rmzelle** [comment]
Hi @XZZ154, sorry for the very late reply. Reference Extractor is not the right tool for your needs. If you import your extracted references into Zotero, Zotero won't recognize that these newly imported items match the items in your document. The Zotero forums are the best place to ask for support with this kind of issue.
