### ISSUE TITLE
Add Endnote reference extraction?

### ISSUE THREAD

**Issue by BellavGFH** [rmzelle/ref-extractor#44]
Ever considered updating ref-extractor.js to also enable the extraction of Endnote references? Although more and more authors use Zotero, Endnote remains stubbornly present. And since the notation in content.xml seems somewhat similar..?

**Endnote:**
`<text:p text:style-name="Endnote" loext:marker-style-name="T37"><text:span text:style-name="T37"><text:s/></text:span><text:span text:style-name="T2">A. Fridman, A. Chirokov, A. Gutsol. Non-thermal atmospheric pressure discharges. J. Phys. D: Appl. Phys. 38 (2005) R1–R24</text:span></text:p>`

**Zotero:**
`<text:tab/>W. Crookes, On Radiant Matter;, in: Popular Science Monthly, Sheffield, UK, 1879: pp. 157–167. https://en.wikisource.org/wiki/Popular_Science_Monthly/Volume_16/December_1879/On_Radiant_Matter_II.</text:p><text:p text:style-name="Bibliography_20_1">`

**Comment by rmzelle** [comment]
Hi @BellavGFH, sorry for the late reply, and thanks for reaching out. I contacted the makers of EndNote a few years ago, and they wrote they might take legal action if I expanded Reference Extractor to support EndNote citations, so I have no interest in pursuing this feature.

EndNote and Zotero also store their citations quite differently in Word documents (the formated references you posted here are not what the tool looks for, instead it extracts reference metadata in a more structured format), so it wouldn't be quite as trivial to support EndNote as it may appear.

**Comment by BellavGFH** [comment]
Hi Rintze,

First of all THX for replying, no matter what time ;))) And THX too for making RefExtractor to begin with!

I understand what you write about EndNote. It is a proprietary program and their behaviour is pretty similar to that of all the others of that family. Although you would expect that folks at a certain time wake up and see stuff for what it is. Then again, I'm not holding my breath. Every time I do an editing job, I still get Word with EndNote refs every time. Even when you instruct them (bloody academics this is! ;))) to deliver the references as RIS. When you repeat your request, you have to explain (again) that no, not an EndNote Dbase, but RIS please? Added to that that my uni has made the specific choice for FOSS, I'm not even going to bore you with the horrors of working/ merging manuscripts of multiple authors with EndNote refs in LibreOffice...

After that, I suppose you get where my question came from? Luckily we have students! ;)))

So THX again Rintze for doing what you did and helping at least some students sleep a bit longer!

Bella


Sep 27, 2024, 05:44 by ***@***.***:
