### ISSUE TITLE
Add documentation

### ISSUE THREAD

**Issue by rmzelle** [rmzelle/ref-extractor#5]
Would be good to point out the ability in Juris-M to reimport cited items, and how things work generally.

**Comment by rmzelle** [comment]
README covered by https://github.com/rmzelle/ref-extractor/commit/4e4c369b628d2259cb4ce99690651c9bd255bc8a, but I should also give more guidance on the page itself.

**Comment by rmzelle** [comment]
Maybe also leave a note at https://www.zotero.org/support/kb/importing_formatted_bibliographies

**Comment by rmzelle** [comment]
Screengrab of Zotero's Document Preferences.

![image](https://cloud.githubusercontent.com/assets/77951/19630377/a01b9a4e-9957-11e6-8113-9e36b11724db.png)

**Comment by rmzelle** [comment]
@fbennett, I'd be happy to list Juris-M as an alternative method to import Zotero references from Word documents, but I couldn't find any good documentation on how that feature works.

**Comment by fbennett** [comment]
Oops, missed the earlier alerts, sorry. It's okay to leave it out.

There is an [old blog post](http://citationstylist.org/2014/05/03/multilingual-zotero-extracting-embedded-references/) that I use for guidance (and to refresh my own memory when that time of the year comes around again). That said, though, I probably won't include the feature when Juris-M is migrated to 5.0; it adds a lot of complexity that would be a burden for maintenance.

A better way to go will be to implement the full functionality (CSL JSON extraction, uploading to a shared library, and document remapping) in an extended version of your extractor. It will probably take less effort to do that than to get extraction running in a Z-5.0-based environment.

**Comment by rmzelle** [comment]
Okay, thanks.

Do you know if document remapping is always necessary? I haven't tested it yet, but if you import a CSL JSON item that has an `uri` (or `uris`) value, Zotero should be able to link the imported item to the reference in the original Word document, no? Or does it ignore URIs on import? I know there have been warnings against backing up via export/import of CSL JSON, because, among other things, it breaks links to embedded Word document references. So I guess it doesn't round-trip? @adam3smith, do you know?

**Comment by adam3smith** [comment]
Zotero indeed ignores the URI/doesn't roundtrip. 
Dan has mentioned that they'd consider allowing roundtrip -- the context there was Zotero RDF, but this would seem to apply here, too, and even more easily. Might require thinking through WRT possible unintended consequences, though.

**Comment by rmzelle** [comment]
@adam3smith, thanks. It would be nice if Zotero users could import exported CSL JSON produced with Reference Extractor and keep the links to the Word reference fields intact. Would be a relatively easy path if you wanted to edit/correct some items in an existing Word document (no need to mess directly with embedded CSL JSON).

**Comment by adam3smith** [comment]
completely agree.

**Comment by rmzelle** [comment]
@dstillman, do you remember the reason not to have URIs roundtrip for CSL JSON export and import? Reference Extractor would be more useful if Zotero would maintain the links between the imported CSL JSON items and the fields in the originating Word document from which the CSL JSON was extracted. (see the comments directly above for more context)
